# Generated by Django 5.2.8 on 2025-11-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('estimated_hours', models.IntegerField()),
                ('importance', models.IntegerField()),
                ('dependencies', models.JSONField(default=list)),
                ('score', models.FloatField(default=0)),
            ],
        ),
    ]
