# Generated by Django 5.2.8 on 2025-11-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='score',
        ),
    ]
