# Generated by Django 5.2.8 on 2025-11-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
